### list developers
GET http://localhost:3000/developers

### get developers
GET http://localhost:3000/developers/dev_FlgTa1fT07gTPoumhcTRY

### post developers
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "Geberson Antonio",
    "email": "geberson@gmail.com",
    "dateOfBirth": "1998-12-23"
}

### update developers
PATCH http://localhost:3000/developers/dev_aeqiwfv9zfQTjLB2s0_p_
Content-Type: application/json

{
    "email": "dsdsds@gmail.com"
}

### remove developers
DELETE http://localhost:3000/developers/dev_FlgTa1fT07gTPoumhcTRY
